### ISSUE TITLE
Background bug

### ISSUE THREAD

**Issue by megum1n** [Zerthox/ClearVision#2] opened 2016-09-19 13:05 UTC
Everytime when i switch windows on my desktop, background in Discord reloads.
https://www.youtube.com/watch?v=1o8K_h1wDSU

**Comment by Zerthox** [comment] 2016-09-19 19:31
I already noticed that myself.
It seems like an issue with urls as CSS variables. They get reloaded everytime you tab out and back in.
I havent found a way to fix without removing the CSS variables it yet, so if you have any ideas, tell me.

**Comment by megum1n** [comment] 2016-09-20 04:55
I have deleted `--background-image: url();` in your style and created the new theme with 
`.app, .callout-backdrop { background-image: url()!important; }`
It helps c:

**Comment by Zerthox** [comment] 2016-09-22 14:18
Yeah it helps for the background, but the problem is, the background image occurs 13x times overall and since I wanna provide customizability, I used CSS variables.
So if you tab out and back in, not only the app bg, but all other occurrencies get reloaded aswell.

**Comment by Zerthox** [comment] 2016-10-16 16:27
This issue will be adressed and fixed with the next release!

**Closed as completed by Zerthox** 2016-10-16 16:27 UTC
Labels: bug
